---
# tasks file for mysql
- name: Banco de dados para o WordPress
  mysql_db: name={{ wp_mysql_db }} state=present
   
- name: Usuario de banco para o WordPress
  mysql_user:
    name={{ wp_mysql_user }}
    password={{ wp_mysql_password }}
    priv=*.*:ALL